import '@testing-library/jest-dom/vitest';
import { afterAll, afterEach, beforeAll } from 'vitest';
import { server } from './msw-node';
import { resetMswAuthState } from './msw-fixtures/auth-handlers';
import { resetMswSearchState } from './msw-fixtures/search-handlers';
import { resetMswAdminState } from './msw-fixtures/admin-handlers';
import { resetMswProfileState } from './msw-fixtures/profile-handlers';
import { resetMswConnectionsState } from './msw-fixtures/connections-handlers';
import { resetMswPitchState } from './msw-fixtures/pitch-handlers';
import { resetMswMisState } from './msw-fixtures/mis-handlers';
import { resetMswScheduleState } from './msw-fixtures/schedule-handlers';
import { resetMswTravelState } from './msw-fixtures/travel-handlers';
import { resetMswMatchmakingState } from './msw-fixtures/matchmaking-handlers';
import { resetMswProfileViewersState } from './msw-fixtures/profile-viewers-handlers';
import { resetMswOnboardingState } from './msw-fixtures/onboarding-handlers';
import { resetMswAdminHomeState } from './msw-fixtures/admin-home-handlers';
import { resetMswAdminDigestState } from './msw-fixtures/admin-digest-handlers';
import { resetMswMatchmakingOpsState } from './msw-fixtures/admin-matchmaking-ops-handlers';
import { useAuthStore } from '@/auth/auth-store';
import { resetInteractionDedup } from '@/lib/interaction-dedup';

beforeAll(() => server.listen({ onUnhandledRequest: 'bypass' }));
afterEach(() => {
  server.resetHandlers();
  resetMswAuthState();
  resetMswSearchState();
  resetMswAdminState();
  resetMswConnectionsState();
  resetMswPitchState();
  resetMswMisState();
  resetMswScheduleState();
  resetMswTravelState();
  resetMswMatchmakingState();
  resetMswProfileViewersState();
  resetMswOnboardingState();
  resetMswAdminHomeState();
  resetMswAdminDigestState();
  resetMswMatchmakingOpsState();
  resetMswProfileState();
  resetInteractionDedup();
  useAuthStore.getState().clear();
  if (typeof localStorage?.clear === 'function') localStorage.clear();
});
afterAll(() => server.close());
