import type { SearchResponse, StartupResultItem, LPResultItem } from '@/features/search/schemas';

// ── Catalogue ───────────────────────────────────────────────────────────────
// A small but varied catalogue used by the MSW `auto` scenario to filter by query
// and filters. Add new entries here when you want to demo a sector/stage/geography
// combination — the filter logic in `search-handlers.ts` does the rest.

export const STARTUP_CATALOGUE: StartupResultItem[] = [
  {
    user_id: '11111111-1111-4000-8000-000000000001',
    name: 'Kapil Sahu',
    organisation: 'Acme Technologies',
    avatar_url: null,
    company_name: 'Acme Technologies',
    sector: 'fintech',
    stage: 'seed',
    one_liner: 'AI for compliance',
    description: 'We help banks automate KYC via agentic LLM workflows.',
    traction: '3 pilot banks, ₹2Cr ARR',
    funding_target_cr: 10.0,
    similarity_score: 0.87,
    ai_rank: 1,
    ai_reason: 'Strong match on sector + stage + traction.',
  },
  {
    user_id: '11111111-1111-4000-8000-000000000002',
    name: 'Priya Rao',
    organisation: 'NeoLedger',
    avatar_url: null,
    company_name: 'NeoLedger',
    sector: 'fintech',
    stage: 'pre_seed',
    one_liner: 'Accounting copilot for SMBs',
    description: 'Auto-bookkeeping via LLM + rules engine.',
    traction: '200 SMBs, 40% MoM growth',
    funding_target_cr: 3.0,
    similarity_score: 0.79,
    ai_rank: 2,
    ai_reason: 'Matches sector; earlier stage than requested.',
  },
  {
    user_id: '11111111-1111-4000-8000-000000000003',
    name: 'Aryan Mehta',
    organisation: 'GreenStack',
    avatar_url: null,
    company_name: 'GreenStack',
    sector: 'climate',
    stage: 'series_a',
    one_liner: 'Carbon-credit accounting for enterprises',
    description: 'Audit-grade tooling for scope-1/2/3 emissions reporting.',
    traction: '14 Fortune-500 customers',
    funding_target_cr: 25.0,
    similarity_score: 0.82,
    ai_rank: 1,
    ai_reason: 'Climate stack with measurable enterprise traction.',
  },
  {
    user_id: '11111111-1111-4000-8000-000000000004',
    name: 'Rhea Iyer',
    organisation: 'Sutra Health',
    avatar_url: null,
    company_name: 'Sutra Health',
    sector: 'healthtech',
    stage: 'seed',
    one_liner: 'AI triage for tier-2 hospitals',
    description: 'Voice-first patient triage in 8 Indian languages.',
    traction: '40 hospitals, 30k triage events/month',
    funding_target_cr: 8.0,
    similarity_score: 0.81,
    ai_rank: 1,
    ai_reason: 'Healthtech with strong adoption in tier-2.',
  },
  {
    user_id: '11111111-1111-4000-8000-000000000005',
    name: 'Vikram Joshi',
    organisation: 'Mosaic Labs',
    avatar_url: null,
    company_name: 'Mosaic Labs',
    sector: 'saas',
    stage: 'pre_a',
    one_liner: 'Vendor onboarding for procurement teams',
    description: 'Automates KYB checks + risk scoring.',
    traction: '40 enterprise customers, $4M ARR',
    funding_target_cr: 18.0,
    similarity_score: 0.74,
    ai_rank: 3,
    ai_reason: 'SaaS with clean ARR signal.',
  },
  {
    user_id: '11111111-1111-4000-8000-000000000006',
    name: 'Sara Pillai',
    organisation: 'Nimbus AI',
    avatar_url: null,
    company_name: 'Nimbus AI',
    sector: 'deeptech',
    stage: 'seed',
    one_liner: 'On-device speech models for edge devices',
    description: 'Sub-100ms ASR on ARM. Runs offline.',
    traction: 'Pilot with 2 hardware OEMs',
    funding_target_cr: 12.0,
    similarity_score: 0.78,
    ai_rank: 2,
    ai_reason: 'Deeptech ASR with hardware partner traction.',
  },
  {
    user_id: '11111111-1111-4000-8000-000000000007',
    name: 'Karan Arora',
    organisation: 'AgriPulse',
    avatar_url: null,
    company_name: 'AgriPulse',
    sector: 'agritech',
    stage: 'series_a',
    one_liner: 'Crop-insurance underwriting via satellite imagery',
    description: 'Loss-event detection from Sentinel-2 + ground sensors.',
    traction: '4 insurers, 6 lakh acres covered',
    funding_target_cr: 30.0,
    similarity_score: 0.83,
    ai_rank: 1,
    ai_reason: 'Agritech with measurable insurance coverage.',
  },
  {
    user_id: '11111111-1111-4000-8000-000000000008',
    name: 'Meera Nair',
    organisation: 'EduCanvas',
    avatar_url: null,
    company_name: 'EduCanvas',
    sector: 'edtech',
    stage: 'pre_seed',
    one_liner: 'Personalised learning paths for K-12',
    description: 'LLM-tutored worksheets aligned to NCERT.',
    traction: '12 schools in beta',
    funding_target_cr: 2.5,
    similarity_score: 0.71,
    ai_rank: 2,
    ai_reason: 'Edtech with curriculum-aligned content.',
  },
  {
    user_id: '11111111-1111-4000-8000-000000000009',
    name: 'Omega Labs',
    organisation: 'Omega',
    company_name: 'Omega Labs',
    sector: 'climate',
    stage: 'seed',
    one_liner: 'Carbon-credit tooling for SMBs',
  },
];

export const LP_CATALOGUE: LPResultItem[] = [
  {
    user_id: '22222222-2222-4000-8000-000000000001',
    name: 'Abhinav Benthia',
    organisation: 'Warmup Ventures',
    designation: 'Partner',
    avatar_url: null,
    fund_name: 'Warmup Fund I',
    aum_cr: 250.0,
    cheque_range_min: 1.0,
    cheque_range_max: 10.0,
    sectors: ['fintech', 'defence'],
    stages: ['seed', 'series_a'],
    geography: ['IN', 'SEA'],
    co_invest_interest: true,
    similarity_score: 0.91,
    ai_rank: 1,
    ai_reason: 'Fund thesis aligns on fintech + early-stage ticket.',
  },
  {
    user_id: '22222222-2222-4000-8000-000000000002',
    name: 'Mira Kapoor',
    organisation: 'Bluestone Capital',
    designation: 'Principal',
    fund_name: 'Bluestone Growth',
    aum_cr: 800.0,
    cheque_range_min: 10.0,
    cheque_range_max: 50.0,
    sectors: ['saas', 'consumer'],
    stages: ['series_a', 'series_b'],
    geography: ['IN', 'US'],
    co_invest_interest: false,
    similarity_score: 0.84,
    ai_rank: 2,
    ai_reason: 'Larger ticket; SaaS-focused.',
  },
  {
    user_id: '22222222-2222-4000-8000-000000000003',
    name: 'Rohan Desai',
    organisation: 'Lighthouse Family Office',
    designation: 'Investment Director',
    fund_name: 'Lighthouse FO',
    aum_cr: 1200.0,
    cheque_range_min: 0.5,
    cheque_range_max: 5.0,
    sectors: ['climate', 'agritech'],
    stages: ['pre_seed', 'seed'],
    geography: ['IN', 'EU'],
    co_invest_interest: true,
    similarity_score: 0.82,
    ai_rank: 3,
    ai_reason: 'Patient capital, climate-tilted thesis.',
  },
  {
    user_id: '22222222-2222-4000-8000-000000000004',
    name: 'Sanjay Iyer',
    organisation: 'Northridge Capital',
    designation: 'General Partner',
    fund_name: 'Northridge Fund III',
    aum_cr: 450.0,
    cheque_range_min: 5.0,
    cheque_range_max: 25.0,
    sectors: ['deeptech', 'healthtech'],
    stages: ['seed', 'series_a'],
    geography: ['IN', 'SEA', 'ME'],
    co_invest_interest: true,
    similarity_score: 0.79,
    ai_rank: 4,
    ai_reason: 'Deeptech / healthtech investor.',
  },
  {
    user_id: '22222222-2222-4000-8000-000000000005',
    name: 'Deepa Krishnan',
    organisation: 'Indus VC',
    designation: 'Partner',
    fund_name: 'Indus Seed',
    aum_cr: 150.0,
    cheque_range_min: 0.5,
    cheque_range_max: 4.0,
    sectors: ['edtech', 'consumer', 'fintech'],
    stages: ['pre_seed', 'seed'],
    geography: ['IN'],
    co_invest_interest: true,
    similarity_score: 0.77,
    ai_rank: 5,
    ai_reason: 'India-only seed-stage investor.',
  },
];

// ── Backwards-compat fixtures used by tests with explicit scenarios ─────────
// Existing tests reference these by name. The `auto` scenario filters the
// catalogue above instead.

export const startupResultsFixture: SearchResponse = {
  results: STARTUP_CATALOGUE.slice(0, 2),
  total: 23,
  target_type: 'startup',
  stage3_applied: true,
  rerank_cap: 20,
  next_cursor: null,
};

export const lpResultsFixture: SearchResponse = {
  results: LP_CATALOGUE.slice(0, 1),
  total: 8,
  target_type: 'lp',
  stage3_applied: true,
  rerank_cap: 20,
  next_cursor: null,
};

export const stage3FallbackFixture: SearchResponse = {
  results: [
    {
      ...STARTUP_CATALOGUE[4]!,
      ai_rank: null,
      ai_reason: null,
    },
  ],
  total: 12,
  target_type: 'startup',
  stage3_applied: false,
  rerank_cap: 20,
  next_cursor: null,
};

export const emptyResultsFixture: SearchResponse = {
  results: [],
  total: 0,
  target_type: 'startup',
  stage3_applied: true,
  rerank_cap: 20,
  next_cursor: null,
};

export const partnerMaskedFixture: SearchResponse = {
  results: [STARTUP_CATALOGUE[8]!],
  total: 1,
  target_type: 'startup',
  stage3_applied: true,
  rerank_cap: 20,
  next_cursor: null,
};
